
obj-$(CONFIG_IPANEMA_POLICY_CFS) += cfs.o
obj-$(CONFIG_IPANEMA_POLICY_CFS_WWC) += cfs_wwc.o
obj-$(CONFIG_IPANEMA_POLICY_CFS_WWC_LOCAL_NEW_UNBLOCK) += cfs_wwc_local_new_unblock.o
obj-$(CONFIG_IPANEMA_POLICY_ULE) += ule.o
obj-$(CONFIG_IPANEMA_POLICY_ULE_WWC) += ule_wwc.o
obj-m += 12300.o
