
obj-$(CONFIG_IPANEMA_POLICY_CFS) += cfs.o
obj-$(CONFIG_IPANEMA_POLICY_CFS_WWC) += cfs_wwc.o
obj-$(CONFIG_IPANEMA_POLICY_CFS_WWC_FLAT) += cfs_wwc_flat.o
obj-$(CONFIG_IPANEMA_POLICY_CFS_WWC_LOCAL_NEW_UNBLOCK) += cfs_wwc_local_new_unblock.o
obj-$(CONFIG_IPANEMA_POLICY_ULE) += ule.o
obj-$(CONFIG_IPANEMA_POLICY_ULE_WWC) += ule_wwc.o
obj-m += 12300.o
obj-m += 10261.o
obj-m += 44530.o
obj-m += cfs_unblock_wwc.o
obj-m += cfs_ticklike_wwc.o
obj-m += cfs_wwc_preempt_on_wakeup.o
obj-m += ule_rip.o
obj-m += ule_wwc_rip.o
