/*
  Automatically generated from an Ipanema specification by the Ipanema compiler
  Copyright (C) 2016 INRIA, LIG, EPFL, I3S
  --- Do not edit this file ---
*/

/* checksum = 13904 */
#define LINUX

#include <linux/delay.h>
#include <linux/ipanema.h>
#include <linux/ipanema_rbtree.h>
#include <linux/ktime.h>
#include <linux/lockdep.h>
#include <linux/module.h>
#include <linux/proc_fs.h>
#include <linux/sched.h>
#include <linux/seq_file.h>
#include <linux/slab.h>
#include <linux/sort.h>
#include <linux/threads.h>

#define ipanema_assert(x) do{if(!(x)) panic("Error in " #x "\n");} while(0)
#define time_to_ticks(x) ktime_to_ns(x)
#define ticks_to_time(x) ns_to_ktime(x)

static char *name = "Simple";
static struct ipanema_module *module;

#define	 CURRENT_0_STATE  1 << 0 /* File "compiler/compiler/compile_misc.ml", line 67, characters 43-50 */
#define	 READY_STATE  1 << 1 /* File "compiler/compiler/compile_misc.ml", line 64, characters 43-50 */
#define	 BLOCKED_STATE	1 << 2 /* File "compiler/compiler/compile_misc.ml", line 64, characters 43-50 */
#define	 TERMINATED_STATE  1 << 3 /* File "compiler/compiler/compile_misc.ml", line 64, characters 43-50 */
#define	 READY_TICK_STATE  1 << 4 /* File "compiler/compiler/compile_misc.ml", line 53, characters 68-75 */
#define	 MIGRATING_STATE  1 << 5 /* File "compiler/compiler/compile_misc.ml", line 54, characters 71-78 */
#define	 ACTIVE_CORES_STATE  1 << 0 /* File "compiler/compiler/compile_misc.ml", line 82, characters 42-49 */
#define	 INACTIVE_CORES_STATE  1 << 1

#define get_policy_current(cpu)    (ipanema_state(cpu).current_0)
#define get_policy_rq(cpu, name)   (ipanema_state(cpu).name)
#define get_policy_core(cpu)       (per_cpu(core, (cpu)))

struct Simple_ipa_process;
struct Simple_ipa_core;
struct Simple_ipa_sched_domain;
struct Simple_ipa_sched_group;

/* definition of protocol states */
struct state_info {
	struct Simple_ipa_process *current_0;
	struct ipanema_rq ready;
};


// At least a READY queue is often shared.
// Optimization: use DEFINE_PER_CPU_ALIGNED(type, name) otherwise.
// See include/linux/percpu-defs.h for more information.
DEFINE_PER_CPU_SHARED_ALIGNED(struct state_info, state_info);

/* definition of core's states */
struct core_state_info {
	cpumask_var_t active_cores;
};


static struct core_state_info cstate_info;

struct Simple_ipa_process {
	/* process attributes
	 *  specified by the scheduling policy
	 *  in the process = {...} declaration
	 */
	int state; // Internal
	struct ipanema_rq *rq; // Internal
	struct rb_node node; // Internal
	struct task_struct * task; // Internal
	int quanta;
	int load;
};

struct Simple_ipa_core {
	/* core attributes
	 *  specified by the scheduling policy
	 *  in the core = {...} declaration
	 */
	int state; // Internal
	int ___sched_domains_idx; // Internal
	int id; // System
	struct Simple_ipa_sched_domain * sd;
	int cload;
};

struct Simple_ipa_sched_group {
	/* group attributes
	 *  specified by the scheduling policy
	 *  in the group = {...} declaration
	 */
	cpumask_var_t cores;
	int capacity;
};

struct Simple_ipa_sched_domain {
	/* domain attributes
	 *  specified by the scheduling policy
	 *  in the domain = {...} declaration
	 */
	int ___sched_group_idx; // Internal
	cpumask_var_t cores; // Internal
	struct Simple_ipa_sched_group * groups;
};


DEFINE_PER_CPU(struct Simple_ipa_core, core);

static int ipanema_Simple_get_metric(struct ipanema_policy *policy,
				     struct task_struct *a)
{
	return ((struct Simple_ipa_process *)policy_metadata(a))->quanta;

}

static int ipanema_Simple_order_process(struct ipanema_policy *policy,
					struct task_struct *a,
					struct task_struct *b)
{
	int v_a = ipanema_Simple_get_metric(policy, a);
	int v_b = ipanema_Simple_get_metric(policy, b);
	return v_a - v_b;
}

static int get_class(int state)
{
	switch(state) {
		case CURRENT_0_STATE: return IPANEMA_RUNNING;
		case READY_STATE: return IPANEMA_READY;
		case BLOCKED_STATE: return IPANEMA_BLOCKED;
		case TERMINATED_STATE: return IPANEMA_TERMINATED;
		case READY_TICK_STATE: return IPANEMA_READY_TICK;
		case MIGRATING_STATE: return IPANEMA_MIGRATING;
		default: return -1;
	}
}

static void ipa_change_proc(struct Simple_ipa_process *proc,
			    struct Simple_ipa_process **dst,
			    int state)
{
	*dst = proc;
	proc->state = state;
	proc->rq = NULL;
	change_state(proc->task, get_class(state), task_cpu(proc->task), NULL);
}

static void ipa_change_queue(struct Simple_ipa_process *proc,
			     struct ipanema_rq *rq, int state)
{
	if (proc->state == CURRENT_0_STATE)
		ipanema_state(task_cpu(proc->task)).current_0 = NULL;
	proc->state = state;
	proc->rq = rq;
	change_state(proc->task, get_class(state), task_cpu(proc->task), rq);
}


static void ipa_change_queue_and_core(struct Simple_ipa_process *proc,
				      struct ipanema_rq *rq, int state,
				      struct Simple_ipa_core *core)
{
	if (proc->state == CURRENT_0_STATE)
		ipanema_state(task_cpu(proc->task)).current_0 = NULL;
	proc->state = state;
	proc->rq = rq;
	change_state(proc->task, get_class(state), core->id, rq);
}

static void set_active_core(struct Simple_ipa_core *core, cpumask_var_t cores,
			    int state)
{
	core->state = state;
	cpumask_set_cpu(core->id, cores);
}

static void set_inactive_core(struct Simple_ipa_core *core, cpumask_var_t cores,
			      int state)
{
	core->state = state;
	cpumask_clear_cpu(core->id, cores);
}

static int ipanema_Simple_new_prepare(struct ipanema_policy *policy,
				      struct process_event *e)
{
	struct Simple_ipa_process *tgt;
	struct task_struct *p = NULL;
	int cpu, dst;
	int cpu_nr, dst_nr;

	p = e->target;
	tgt = kzalloc(sizeof(struct Simple_ipa_process), GFP_ATOMIC);
	if (!tgt)
		return -1;
	policy_metadata(p) = tgt;
	tgt->task = p;
	tgt->rq = NULL;
	tgt->quanta = 0;

	/* Choose the core with the lowest number of READY + RUNNING tasks */
	dst = p->cpu;
	dst_nr = ipanema_state(dst).ready.nr_tasks + (ipanema_state(dst).current_0 ? 1 : 0);
	for_each_cpu(cpu, cstate_info.active_cores) {
		cpu_nr = ipanema_state(cpu).ready.nr_tasks + (ipanema_state(cpu).current_0 ? 1 : 0);
		if (cpu_nr < dst_nr) {
			dst = cpu;
			dst_nr = cpu_nr;
		}
	}

	return dst;
}

static void ipanema_Simple_new_place(struct ipanema_policy *policy,
				     struct process_event *e)
{
	struct Simple_ipa_process * tgt = policy_metadata(e->target);
	int idlecore_10;

	idlecore_10 = task_cpu(e->target);
	ipa_change_queue_and_core(tgt, &ipanema_state(idlecore_10).ready,
				  READY_STATE, &ipanema_core(idlecore_10));
}

static void ipanema_Simple_new_end(struct ipanema_policy *policy,
				   struct process_event *e)
{
	IPA_EMERG_SAFE("[%d] post new on core %d\n",
		       e->target->pid, e->target->cpu);
}

static void ipanema_Simple_detach(struct ipanema_policy *policy,
				  struct process_event *e)
/* need to free the process metadata memory */
{
	struct Simple_ipa_process * tgt = policy_metadata(e->target);

	ipa_change_queue(tgt, NULL, TERMINATED_STATE);
	kfree(tgt);
}

static void ipanema_Simple_tick(struct ipanema_policy *policy,
				struct process_event *e)
{
	struct Simple_ipa_process * tgt = policy_metadata(e->target);

	tgt->quanta = tgt->quanta + 1;
	if ((tgt->quanta % 10) == 0) {
		ipa_change_queue(tgt,
				 &ipanema_state(task_cpu(tgt->task)).ready,
				 READY_TICK_STATE);
	}

}

static void ipanema_Simple_yield(struct ipanema_policy *policy,
				 struct process_event *e)
{
	struct Simple_ipa_process * tgt = policy_metadata(e->target);

	ipa_change_queue(tgt, &ipanema_state(task_cpu(tgt->task)).ready,
			 READY_STATE);
}

static void ipanema_Simple_block(struct ipanema_policy *policy,
				 struct process_event *e)
{
	struct Simple_ipa_process * tgt = policy_metadata(e->target);

	ipa_change_queue(tgt, NULL, BLOCKED_STATE);
}

static int ipanema_Simple_unblock_prepare(struct ipanema_policy *policy,
					  struct process_event *e)
{
	struct task_struct *p = e->target;
	int dst, cpu;
	int cpu_nr, dst_nr;

	dst = p->cpu;
	dst_nr = ipanema_state(dst).ready.nr_tasks + (ipanema_state(dst).current_0 ? 1 : 0);
	for_each_cpu(cpu, cstate_info.active_cores) {
		cpu_nr = ipanema_state(cpu).ready.nr_tasks + (ipanema_state(cpu).current_0 ? 1 : 0);
		if (cpu_nr < dst_nr) {
			dst = cpu;
			dst_nr = cpu_nr;
		}
	}

	return dst;
}

static void ipanema_Simple_unblock_place(struct ipanema_policy *policy,
					 struct process_event *e)
{
	struct Simple_ipa_process * tgt = policy_metadata(e->target);
	int idlecore_11;

	idlecore_11 = task_cpu(e->target);
	ipa_change_queue_and_core(tgt, &ipanema_state(idlecore_11).ready,
				  READY_STATE, &ipanema_core(idlecore_11));
}

static void ipanema_Simple_unblock_end(struct ipanema_policy *policy,
				       struct process_event *e)
{
	IPA_EMERG_SAFE("[%d] post unblock on core %d\n",
		       e->target->pid, e->target->cpu);
}

static void ipanema_Simple_schedule(struct ipanema_policy *policy,
				    unsigned int cpu)
{
	struct task_struct *p;
	struct Simple_ipa_process * _fresh_12;

	p = ipanema_first_task(&ipanema_state(cpu).ready);
	if (!p)
		return;

	_fresh_12 = policy_metadata(p);
	if (_fresh_12) {
		ipa_change_proc(_fresh_12, &ipanema_state(cpu).current_0,
				CURRENT_0_STATE);
	}
}

static void ipanema_Simple_core_entry(struct ipanema_policy *policy,
				      struct core_event *e)
{
	struct Simple_ipa_core * tgt = &ipanema_core(e->target);

	set_active_core(tgt, cstate_info.active_cores, ACTIVE_CORES_STATE);
}

static void ipanema_Simple_core_exit(struct ipanema_policy *policy,
				     struct core_event *e)
{
	struct Simple_ipa_core * tgt = &ipanema_core(e->target);

	set_inactive_core(tgt, cstate_info.active_cores, INACTIVE_CORES_STATE);
	/* TODO: Migrate all tasks to another cpu */
}


static void ipanema_Simple_newly_idle(struct ipanema_policy *policy,
				      struct core_event *e)
{
	return;
}

static void ipanema_Simple_enter_idle(struct ipanema_policy *policy,
				      struct core_event *e)
{
	return;
}

static void ipanema_Simple_exit_idle(struct ipanema_policy *policy,
				     struct core_event *e)
{
	return;
}

static void ipanema_Simple_balancing(struct ipanema_policy *policy,
				     struct core_event *e)
{

}

static int ipanema_Simple_init(struct ipanema_policy * policy)
{
	return 0;
}

static bool ipanema_Simple_attach(struct ipanema_policy * policy,
				  struct task_struct * _fresh_13,
				  char * command)
{
	return true;
}

int ipanema_Simple_free_metadata(struct ipanema_policy *policy)
{
	kfree(policy->data);
	return 0;
}

int ipanema_Simple_can_be_default(struct ipanema_policy *policy)
{
	return 1;
}

struct ipanema_module_routines ipanema_Simple_routines =
{
	.order_process	  = ipanema_Simple_order_process,
	.get_metric	  = ipanema_Simple_get_metric,
	.new_prepare	  = ipanema_Simple_new_prepare,
	.new_place	  = ipanema_Simple_new_place,
	.new_end	  = ipanema_Simple_new_end,
	.tick		  = ipanema_Simple_tick,
	.yield		  = ipanema_Simple_yield,
	.block		  = ipanema_Simple_block,
	.unblock_prepare  = ipanema_Simple_unblock_prepare,
	.unblock_place	  = ipanema_Simple_unblock_place,
	.unblock_end	  = ipanema_Simple_unblock_end,
	.terminate	  = ipanema_Simple_detach,
	.schedule	  = ipanema_Simple_schedule,
	.newly_idle	  = ipanema_Simple_newly_idle,
	.enter_idle	  = ipanema_Simple_enter_idle,
	.exit_idle	  = ipanema_Simple_exit_idle,
	.balancing_select = ipanema_Simple_balancing,
	.core_entry	  = ipanema_Simple_core_entry,
	.core_exit	  = ipanema_Simple_core_exit,
	.init		  = ipanema_Simple_init,
	.free_metadata	  = ipanema_Simple_free_metadata,
	.can_be_default	  = ipanema_Simple_can_be_default,
	.attach		  = ipanema_Simple_attach
};

static bool create_scheduling_domain(int cpu, int level)
{
    int c, idx;
    struct topology_level *topology = per_cpu(topology_levels, cpu);
    struct topology_level current_topology = topology[level];

    struct Simple_ipa_sched_domain sd = {}, *sds;
    int nb_existing_domains;
    nb_existing_domains = ipanema_core(cpu).___sched_domains_idx;

    if (cpumask_weight(current_topology.cores) <= 1)
      return false;

    for_each_cpu(c, current_topology.cores) {
      struct Simple_ipa_sched_group sg = {};

      if (cpumask_test_cpu(c, sd.cores))
	continue;

      if (nb_existing_domains == 0) {
	cpumask_set_cpu(c, sg.cores);

      } else {
	if (nb_existing_domains <= 0)
	  /*
	   * This is possible because the topology is
	   * created in the kernel using
	   * for_each_possible_cpu(), which means it
	   * tends to add dozens of cores at the last
	   * level which never actually exist. These
	   * cores won't have any scheduling levels yet,
	   * and we don't want them in our hierarchy.
	   */
	  continue;

	sds = ipanema_core(c).sd;
	cpumask_or(sg.cores, sg.cores,
	     sds[nb_existing_domains - 1].cores);
      }
      sg.capacity = cpumask_weight(sg.cores);
      cpumask_or(sd.cores, sd.cores, sg.cores);
      sd.___sched_group_idx++;
      sd.groups = krealloc(sd.groups,
	       sizeof(*sd.groups)
	       * sd.___sched_group_idx, GFP_ATOMIC);
      sd.groups[sd.___sched_group_idx - 1] = sg;
    }

    /* Useless scheduling domain, ignore it. */
    if (sd.___sched_group_idx < 2) {
	  kfree(sd.groups);
	  return false;
    }

    ipanema_core(cpu).___sched_domains_idx++;
    ipanema_core(cpu).sd = krealloc(ipanema_core(cpu).sd,
				sizeof(*ipanema_core(cpu).sd)
				* ipanema_core(cpu).___sched_domains_idx,
				GFP_ATOMIC);
    idx = ipanema_core(cpu).___sched_domains_idx - 1;
    ipanema_core(cpu).sd[idx] = sd;

    return true;
}

static int proc_show(struct seq_file *s, void *p)
{
	long cpu = (long) s->private;
	struct task_struct *pos, *n;
	struct Simple_ipa_process *pr, *curr_proc;
	int load_sum = 0;

	ipanema_lock_core(cpu);
	pr = ipanema_state(cpu).current_0;
	seq_printf(s, "CPU: %ld\n", cpu);
	seq_printf(s, "RUNNING (policy): %d (%d)\n",
	pr ? pr->task->pid : -1,
	pr ? pr->load : -1);
	n = per_cpu(ipanema_current, cpu);
	seq_printf(s, "RUNNING (runtime): %d\n", n ? n->pid : -1);
	load_sum += pr ? pr->load : 0;
	seq_printf(s, "READY: ");
	rbtree_postorder_for_each_entry_safe(pos, n,
					     &(ipanema_state(cpu).ready).root,
					     ipanema_metadata.node_runqueue) {
		curr_proc = (struct Simple_ipa_process *)policy_metadata(pos);
		load_sum += curr_proc->load;
		seq_printf(s, "%d (%d) -> ", pos->pid, curr_proc->load);
	}

	seq_printf(s, "\n");
	seq_printf(s, "COUNT(READY) = %d\n", count(IPANEMA_READY, cpu));
	seq_printf(s, "nr_ready = %d\n", ipanema_state(cpu).ready.nr_tasks);
	seq_printf(s, "load = %d\n", ipanema_core(cpu).cload);
	seq_printf(s, "load_sum = %d\n", load_sum);

	ipanema_unlock_core(cpu);

	return 0;
}

static int proc_open(struct inode *inode, struct file *file)
{
	long cpu;

	kstrtol(file->f_path.dentry->d_iname, 10, &cpu);
	return single_open(file, proc_show, (void *)cpu);
}

static struct file_operations proc_fops = {

	.owner	 = THIS_MODULE,
	.open	 = proc_open,
	.read	 = seq_read,
	.llseek	 = seq_lseek,
	.release = single_release
};

int init_module(void)
{
	int res;
	int cpu, test_cpu, level;
	int idx, sd_idx, sg_idx;
	bool created = false, unseen = false;
	cpumask_t *sd_mask;
	char buf[NR_CPUS * 2];
	struct Simple_ipa_sched_domain *sd;
	struct Simple_ipa_sched_group *sg;
	struct proc_dir_entry *procdir = NULL;
	char procbuf[10];

	/* Initialize scheduler variables with non-const value (function call) */

	for_each_possible_cpu(cpu) {
		ipanema_core(cpu).id = cpu;
		/* READY rq */
		ipanema_state(cpu).ready.cpu = cpu;
		ipanema_state(cpu).ready.nr_tasks = 0;
		ipanema_state(cpu).ready.root.rb_node = NULL;
		ipanema_state(cpu).ready.state = get_class(READY_STATE);

		/* /\* BLOCKED rq *\/ */
		/* per_cpu(state_info, cpu).blocked.cpu = cpu; */
		/* per_cpu(state_info, cpu).blocked.nr_tasks = 0; */
		/* per_cpu(state_info, cpu).blocked.root.rb_node = NULL; */
		/* per_cpu(state_info, cpu).blocked.state = get_class(BLOCKED_STATE); */

		/* /\* TERMINATED rq *\/ */
		/* per_cpu(state_info, cpu).terminated.cpu = cpu; */
		/* per_cpu(state_info, cpu).terminated.nr_tasks = 0; */
		/* per_cpu(state_info, cpu).terminated.root.rb_node = NULL; */
		/* per_cpu(state_info, cpu).terminated.state = get_class(TERMINATED_STATE); */
	}

	/* allocation of every cpumask_var_t of struct core_state_info */
	if (!zalloc_cpumask_var(&(cstate_info.active_cores), GFP_KERNEL)) {
		res = -ENOMEM;
		goto clean_cpumask_var;
	}


	for(level = 0; level < nb_topology_levels; level ++) {
		created = false;
		for_each_present_cpu(cpu) /* is it 'possible' cpus ? */{
			created |= create_scheduling_domain(cpu,level);
		}
		if (!created)
			continue;

		unseen = false;
		for_each_present_cpu(cpu) {
			idx = ipanema_core(cpu).___sched_domains_idx - 1;
			sd_mask = ipanema_core(cpu).sd[idx].cores;

			for_each_present_cpu(test_cpu) {
				if (!cpumask_test_cpu(test_cpu, sd_mask)) {
					unseen = true;
					goto end;
				}
			}
		}

		/*
		 * Once we've seen all present CPUs, we just exit. The next
		 * scheduling domains will be useless and/or duplicates.
		*/
end:
		if (!unseen)
			break;
	}

	IPA_DBG_SAFE("Scheduling domains\n");
	IPA_DBG_SAFE("========================================================="
		     "======================\n");
	IPA_DBG_SAFE("nb_topology_levels = %d\n", nb_topology_levels);
	for_each_present_cpu(cpu) {
		IPA_DBG_SAFE("CPU %d:\n", cpu);
		for (sd_idx = 0;
		     sd_idx < ipanema_core(cpu).___sched_domains_idx;
		     sd_idx++) {
			sd = &ipanema_core(cpu).sd[sd_idx];

			if (!sd)
				continue;

			cpumap_print_to_pagebuf(true, buf, sd->cores);
			IPA_DBG_SAFE("\tSD %d: %d, %s",
				     sd_idx, cpumask_weight(sd->cores), buf);

			for (sg_idx = 0;
			     sg_idx < sd->___sched_group_idx;
			     sg_idx++) {
				sg = &sd->groups[sg_idx];

				if (!sg)
					continue;

				cpumap_print_to_pagebuf(true, buf, sg->cores);
				IPA_DBG_SAFE("\t\tSG %d: %d, %s", sg_idx,
					     cpumask_weight(sg->cores), buf);
			}
		}
	}

	IPA_DBG_SAFE("========================================================="
		     "======================\n");

	module = kmalloc(sizeof(struct ipanema_module), GFP_KERNEL);
	if (!module)

	{
		res = -ENOMEM;
		goto clean_cpumask_var;

	}

	module->name = name;
	module->routines = &ipanema_Simple_routines;
	module->kmodule = THIS_MODULE;

	if ((res = ipanema_add_module(module)))
	{
		switch (res)
		{
			case -ETOOMANYMODULES:
			  printk("[IPANEMA] ERROR: too many loaded modules.\n");
			  break;

			case -EINVAL:
			  printk("[IPANEMA] ERROR: unable to load module. A module with "
			  "the same name is already loaded.\n");
			  break;

			default:
			  printk("[IPANEMA] ERROR: couldn't load module.\n");

		}
		goto clean_module;

	}

	/* Create /proc/bl_simple_decl/<cpu> files */
	procdir = proc_mkdir(name, NULL);
	if (!procdir) {
		pr_info("%s: /proc/%s creation failed\n", name, name);
		goto clean_module;
	}
	for_each_possible_cpu(cpu) {
		scnprintf(procbuf, 10, "%d", cpu);
		if (!proc_create(procbuf, 0444, procdir, &proc_fops))
			pr_info("%s: /proc/%s/%s creation failed\n",
				name, name, procbuf);
	}

	return 0;

 clean_module:
	kfree(module);
 clean_cpumask_var:
	/* deallocation of every cpumask_var_t of struct core_state_info */
	free_cpumask_var(cstate_info.active_cores);

	return res;

}

void cleanup_module(void)
{
	int res;

        remove_proc_subtree(name, NULL);
        
        res = ipanema_remove_module(module);
	if (!res)
		goto end;
	switch (res) {
	case -EMODULENOTFOUND:
		printk ("[IPANEMA] ERROR: module not found... Shouldn't happen !\n");
		/* We can safely exit. */
		break;
	case -EMODULEINUSE:
		printk ("[IPANEMA] ERROR: module in use! Remove all instances from /proc/ipanema_policies. Shouldn't happen\n");
		break;
	default:
		printk ("[IPANEMA] ERROR: unknown error (%d).\n", res);
	}
	return;

end:
        kfree(module);
        /* deallocation of every cpumask_var_t of struct core_state_info */
        free_cpumask_var(cstate_info.active_cores);
}

MODULE_AUTHOR("Ipanema Compiler");
MODULE_DESCRIPTION("Simple scheduling policy");
MODULE_LICENSE("GPL");
