/*
  Automatically generated from an Ipanema specification by the Ipanema compiler
  Copyright (C) 2016 INRIA, LIG, EPFL, I3S
  --- Do not edit this file ---
*/

/* checksum = 13904 */
#define LINUX

#include <linux/delay.h>
#include <linux/ipanema.h>
#include <linux/ipanema_rq.h>
#include <linux/ktime.h>
#include <linux/lockdep.h>
#include <linux/module.h>
#include <linux/proc_fs.h>
#include <linux/sched.h>
#include <linux/seq_file.h>
#include <linux/slab.h>
#include <linux/sort.h>
#include <linux/threads.h>

#define ipanema_assert(x) do{if(!(x)) panic("Error in " #x "\n");} while(0)
#define time_to_ticks(x) ktime_to_ns(x)
#define ticks_to_time(x) ns_to_ktime(x)

static char *name = "Simple";
static struct ipanema_module *module;

#define	 CURRENT_0_STATE  1 << 0 /* File "compiler/compiler/compile_misc.ml", line 67, characters 43-50 */
#define	 READY_STATE  1 << 1 /* File "compiler/compiler/compile_misc.ml", line 64, characters 43-50 */
#define	 BLOCKED_STATE	1 << 2 /* File "compiler/compiler/compile_misc.ml", line 64, characters 43-50 */
#define	 TERMINATED_STATE  1 << 3 /* File "compiler/compiler/compile_misc.ml", line 64, characters 43-50 */
#define	 READY_TICK_STATE  1 << 4 /* File "compiler/compiler/compile_misc.ml", line 53, characters 68-75 */
#define	 MIGRATING_STATE  1 << 5 /* File "compiler/compiler/compile_misc.ml", line 54, characters 71-78 */
#define	 ACTIVE_CORES_STATE  1 << 0 /* File "compiler/compiler/compile_misc.ml", line 82, characters 42-49 */
#define	 INACTIVE_CORES_STATE  1 << 1

#define get_policy_current(cpu)    (ipanema_state(cpu).current_0)
#define get_policy_rq(cpu, name)   (ipanema_state(cpu).name)
#define get_policy_core(cpu)       (per_cpu(core, (cpu)))

struct Simple_ipa_process;
struct Simple_ipa_core;
struct Simple_ipa_sched_domain;
struct Simple_ipa_sched_group;

/* definition of protocol states */
struct state_info {
	struct Simple_ipa_process *current_0;
	struct ipanema_rq ready;
};


// At least a READY queue is often shared.
// Optimization: use DEFINE_PER_CPU_ALIGNED(type, name) otherwise.
// See include/linux/percpu-defs.h for more information.
DEFINE_PER_CPU_SHARED_ALIGNED(struct state_info, state_info);

/* definition of core's states */
struct core_state_info {
	cpumask_t active_cores;
};


static struct core_state_info cstate_info;

struct Simple_ipa_process {
	/* process attributes
	 *  specified by the scheduling policy
	 *  in the process = {...} declaration
	 */
	int state; // Internal
	struct ipanema_rq *rq; // Internal
	struct rb_node node; // Internal
	struct task_struct * task; // Internal
	int quanta;
	int load;
	struct list_head list;
};

struct Simple_ipa_core {
	/* core attributes
	 *  specified by the scheduling policy
	 *  in the core = {...} declaration
	 */
	enum ipanema_core_state state; // Internal
	int ___sched_domains_idx; // Internal
	int id; // System
	struct Simple_ipa_sched_domain * sd;
	int cload;
};

struct Simple_ipa_sched_group {
	/* group attributes
	 *  specified by the scheduling policy
	 *  in the group = {...} declaration
	 */
	cpumask_t cores;
	int capacity;
};

/*
 * Example of topology:
 *
 *    O----------[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15]
 *    |           /         |              |          \
 *    O----[0 1 2 3]-----[4 5 6 7]----[8 9 10 11]-----[12 13 14 15]
 *    |    /      \      /      \      /       \        /        \
 *    O--[0 1]--[2 3]--[4 5]--[6 7]--[8 9]--[10 11]--[12 13]--[14 15]
 *    |
 *   Simple_ipa_topology
 */
struct Simple_ipa_sched_domain {
	/* domain attributes
	 *  specified by the scheduling policy
	 *  in the domain = {...} declaration
	 */
	struct list_head siblings;  // link domains of the same level
	struct Simple_ipa_sched_domain *parent;
	int ___sched_group_idx; // Internal
	cpumask_t cores; // Internal
	spinlock_t lock;
	int flags; // Internal
	struct Simple_ipa_sched_group *groups;
	ktime_t next_balance;
	unsigned int idle_count, periodic_count;
};

static struct list_head *Simple_ipa_topology;
static unsigned int Simple_ipa_nr_topology_levels;

DEFINE_PER_CPU(struct Simple_ipa_core, core);

int ipanema_Simple_order_process(struct task_struct *a,
				 struct task_struct *b)
{
	struct Simple_ipa_process *pa = policy_metadata(a);
	struct Simple_ipa_process *pb = policy_metadata(b);

	return pa->quanta - pb->quanta;
}

static int get_class(int state)
{
	switch(state) {
		case CURRENT_0_STATE: return IPANEMA_RUNNING;
		case READY_STATE: return IPANEMA_READY;
		case BLOCKED_STATE: return IPANEMA_BLOCKED;
		case TERMINATED_STATE: return IPANEMA_TERMINATED;
		case READY_TICK_STATE: return IPANEMA_READY_TICK;
		case MIGRATING_STATE: return IPANEMA_MIGRATING;
		default: return -1;
	}
}

static void ipa_change_proc(struct Simple_ipa_process *proc,
			    struct Simple_ipa_process **dst,
			    int state)
{
	*dst = proc;
	proc->state = state;
	proc->rq = NULL;
	change_state(proc->task, get_class(state), task_cpu(proc->task), NULL);
}

static void ipa_change_queue(struct Simple_ipa_process *proc,
			     struct ipanema_rq *rq, int state)
{
	if (proc->state == CURRENT_0_STATE)
		ipanema_state(task_cpu(proc->task)).current_0 = NULL;
	proc->state = state;
	proc->rq = rq;
	change_state(proc->task, get_class(state), task_cpu(proc->task), rq);
}


static void ipa_change_queue_and_core(struct Simple_ipa_process *proc,
				      struct ipanema_rq *rq, int state,
				      struct Simple_ipa_core *core)
{
	if (proc->state == CURRENT_0_STATE)
		ipanema_state(task_cpu(proc->task)).current_0 = NULL;
	proc->state = state;
	proc->rq = rq;
	change_state(proc->task, get_class(state), core->id, rq);
}

static void set_active_core(struct Simple_ipa_core *core, cpumask_t *cores)
{
	core->state = IPANEMA_ACTIVE_CORE;
	cpumask_set_cpu(core->id, cores);
}

static void set_inactive_core(struct Simple_ipa_core *core, cpumask_t *cores)
{
	core->state = IPANEMA_IDLE_CORE;
	cpumask_clear_cpu(core->id, cores);
}

static enum ipanema_core_state
ipanema_Simple_get_core_state(struct ipanema_policy *policy,
			      struct core_event *e)
{
	return ipanema_core(e->target).state;
}

static int ipanema_Simple_new_prepare(struct ipanema_policy *policy,
				      struct process_event *e)
{
	struct Simple_ipa_process *tgt;
	struct task_struct *p = NULL;
	int cpu, dst;
	int cpu_nr, dst_nr;

	p = e->target;
	tgt = kzalloc(sizeof(struct Simple_ipa_process), GFP_ATOMIC);
	if (!tgt)
		return -1;
	policy_metadata(p) = tgt;
	tgt->task = p;
	tgt->rq = NULL;
	tgt->quanta = 0;
	INIT_LIST_HEAD(&tgt->list);

	/* Choose the core with the lowest number of READY + RUNNING tasks */
	dst = p->cpu;
	dst_nr = ipanema_state(dst).ready.nr_tasks + (ipanema_state(dst).current_0 ? 1 : 0);
	for_each_cpu(cpu, &cstate_info.active_cores) {
		cpu_nr = ipanema_state(cpu).ready.nr_tasks + (ipanema_state(cpu).current_0 ? 1 : 0);
		if (cpu_nr < dst_nr) {
			dst = cpu;
			dst_nr = cpu_nr;
		}
	}

	return dst;
}

static void ipanema_Simple_new_place(struct ipanema_policy *policy,
				     struct process_event *e)
{
	struct Simple_ipa_process * tgt = policy_metadata(e->target);
	int idlecore_10;

	idlecore_10 = task_cpu(e->target);
	ipa_change_queue_and_core(tgt, &ipanema_state(idlecore_10).ready,
				  READY_STATE, &ipanema_core(idlecore_10));
}

static void ipanema_Simple_new_end(struct ipanema_policy *policy,
				   struct process_event *e)
{
	pr_info("[%d] post new on core %d\n",
		       e->target->pid, e->target->cpu);
}

static void ipanema_Simple_detach(struct ipanema_policy *policy,
				  struct process_event *e)
/* need to free the process metadata memory */
{
	struct Simple_ipa_process * tgt = policy_metadata(e->target);

	ipa_change_queue(tgt, NULL, TERMINATED_STATE);
	kfree(tgt);
}

static void ipanema_Simple_tick(struct ipanema_policy *policy,
				struct process_event *e)
{
	struct Simple_ipa_process * tgt = policy_metadata(e->target);

	tgt->quanta = tgt->quanta + 1;
	if ((tgt->quanta % 10) == 0) {
		ipa_change_queue(tgt,
				 &ipanema_state(task_cpu(tgt->task)).ready,
				 READY_TICK_STATE);
	}

}

static void ipanema_Simple_yield(struct ipanema_policy *policy,
				 struct process_event *e)
{
	struct Simple_ipa_process * tgt = policy_metadata(e->target);

	ipa_change_queue(tgt, &ipanema_state(task_cpu(tgt->task)).ready,
			 READY_STATE);
}

static void ipanema_Simple_block(struct ipanema_policy *policy,
				 struct process_event *e)
{
	struct Simple_ipa_process * tgt = policy_metadata(e->target);

	ipa_change_queue(tgt, NULL, BLOCKED_STATE);
}

static int ipanema_Simple_unblock_prepare(struct ipanema_policy *policy,
					  struct process_event *e)
{
	struct task_struct *p = e->target;
	int dst, cpu;
	int cpu_nr, dst_nr;

	dst = p->cpu;
	dst_nr = ipanema_state(dst).ready.nr_tasks + (ipanema_state(dst).current_0 ? 1 : 0);
	for_each_cpu(cpu, &cstate_info.active_cores) {
		cpu_nr = ipanema_state(cpu).ready.nr_tasks + (ipanema_state(cpu).current_0 ? 1 : 0);
		if (cpu_nr < dst_nr) {
			dst = cpu;
			dst_nr = cpu_nr;
		}
	}

	return dst;
}

static void ipanema_Simple_unblock_place(struct ipanema_policy *policy,
					 struct process_event *e)
{
	struct Simple_ipa_process * tgt = policy_metadata(e->target);
	int idlecore_11;

	idlecore_11 = task_cpu(e->target);
	ipa_change_queue_and_core(tgt, &ipanema_state(idlecore_11).ready,
				  READY_STATE, &ipanema_core(idlecore_11));
}

static void ipanema_Simple_unblock_end(struct ipanema_policy *policy,
				       struct process_event *e)
{
	pr_info("[%d] post unblock on core %d\n",
		       e->target->pid, e->target->cpu);
}

static void ipanema_Simple_schedule(struct ipanema_policy *policy,
				    unsigned int cpu)
{
	struct task_struct *p;
	struct Simple_ipa_process * _fresh_12;

	p = ipanema_first_task(&ipanema_state(cpu).ready);
	if (!p)
		return;

	_fresh_12 = policy_metadata(p);
	if (_fresh_12) {
		ipa_change_proc(_fresh_12, &ipanema_state(cpu).current_0,
				CURRENT_0_STATE);
	}
}

static void ipanema_Simple_core_entry(struct ipanema_policy *policy,
				      struct core_event *e)
{
	struct Simple_ipa_core * tgt = &ipanema_core(e->target);

	set_active_core(tgt, &cstate_info.active_cores);
}

static void ipanema_Simple_core_exit(struct ipanema_policy *policy,
				     struct core_event *e)
{
	struct Simple_ipa_core * tgt = &ipanema_core(e->target);

	set_inactive_core(tgt, &cstate_info.active_cores);
	/* TODO: Migrate all tasks to another cpu */
}

static void ipanema_Simple_load_balance(struct ipanema_policy *policy,
					struct core_event *e,
					struct Simple_ipa_sched_domain *sd)
{
	unsigned int cpu = e->target;
	unsigned int victim, busiest = cpu;
	unsigned int nr_victim, nr_cpu, nr_busiest = get_policy_rq(cpu, ready).nr_tasks;
	struct task_struct *p = NULL;
	struct Simple_ipa_process *tgt;
	LIST_HEAD(stolen_tasks);
	unsigned int nr_theft;
	unsigned int nr_dequeued = 0, nr_enqueued = 0;
	unsigned long flags;
	ktime_t old;

	/* Select the busiest core */
	for_each_cpu(victim, &sd->cores) {
		nr_victim = get_policy_rq(victim, ready).nr_tasks;
		if (nr_victim > nr_busiest + 1) {
			busiest = victim;
			nr_busiest = nr_victim;
		}
	}
	if (cpu == busiest)
		goto forward_next_balance;

	/*
	 * Lock the busiest core and steal enough tasks to balance cpu and
	 * busiest
	 */
	local_irq_save(flags);
	if (!ipanema_trylock_core(busiest)) {
		local_irq_restore(flags);
		goto forward_next_balance;
	}
	nr_busiest = get_policy_rq(busiest, ready).nr_tasks;
	nr_cpu = get_policy_rq(cpu, ready).nr_tasks;
	nr_theft = (nr_busiest - nr_cpu) / 2;
	while (nr_theft--) {
		p = ipanema_first_task(&get_policy_rq(busiest, ready));
		if (!p)
			continue;
		if (ipanema_task_state(p) != IPANEMA_READY)
			continue;

		tgt = policy_metadata(p);
		list_add(&tgt->list, &stolen_tasks);
		tgt->rq = NULL;
		change_state(p, IPANEMA_MIGRATING, cpu, NULL);
		nr_dequeued++;
	}
	ipanema_unlock_core(busiest);

	/*
	 * Lock cpu and add tasks to READY runqueue
	 */
	ipanema_lock_core(cpu);
	while (!list_empty(&stolen_tasks)) {
		tgt = list_first_entry(&stolen_tasks, struct Simple_ipa_process,
				       list);
		list_del_init(&tgt->list);
		p = tgt->task;
		tgt->rq = &get_policy_rq(cpu, ready);
		change_state(p, IPANEMA_READY, cpu, tgt->rq);
		nr_enqueued++;
	}
	ipanema_unlock_core(cpu);
	local_irq_restore(flags);

forward_next_balance:
	/* Update sd->next_balance */
	old = sd->next_balance;
	sd->next_balance = ktime_add(ktime_get(),
				     ms_to_ktime(10 * cpumask_weight(&sd->cores)));
}

/* Called periodically by the runtime */
static void ipanema_Simple_balancing(struct ipanema_policy *policy,
				     struct core_event *e)
{
	ktime_t now = ktime_get();
	struct Simple_ipa_core *c = &ipanema_core(e->target);
	struct Simple_ipa_sched_domain *sd;
	int i;

	for (i = 0; i < c->___sched_domains_idx; i++) {
		sd = &c->sd[i];
		if (ktime_before(sd->next_balance, now)) {
			sd->periodic_count++;
			ipanema_Simple_load_balance(policy, e, sd);
		}
	}
}

/*
 * Called with no lock held.
 */
static void ipanema_Simple_newly_idle(struct ipanema_policy *policy,
				      struct core_event *e)
{
	struct Simple_ipa_core *c = &ipanema_core(e->target);
	struct Simple_ipa_sched_domain *sd;
	int i, cpu = e->target;

	for (i = 0; i < c->___sched_domains_idx; i++) {
		sd = &c->sd[i];
		sd->idle_count++;
		ipanema_Simple_load_balance(policy, e, sd);
		if (ipanema_state(cpu).ready.nr_tasks > 0)
			break;
	}
}

static void ipanema_Simple_enter_idle(struct ipanema_policy *policy,
				      struct core_event *e)
{
	/* set_inactive_core(&ipanema_core(e->target), &cstate_info.active_cores, */
	/*		  INACTIVE_CORES_STATE); */
}

static void ipanema_Simple_exit_idle(struct ipanema_policy *policy,
				     struct core_event *e)
{
	/* set_active_core(&ipanema_core(e->target), &cstate_info.active_cores, */
	/*		ACTIVE_CORES_STATE); */
}

static int ipanema_Simple_init(struct ipanema_policy * policy)
{
	return 0;
}

static bool ipanema_Simple_attach(struct ipanema_policy * policy,
				  struct task_struct * _fresh_13,
				  char * command)
{
	return true;
}

int ipanema_Simple_free_metadata(struct ipanema_policy *policy)
{
	kfree(policy->data);
	return 0;
}

int ipanema_Simple_can_be_default(struct ipanema_policy *policy)
{
	return 1;
}

struct ipanema_module_routines ipanema_Simple_routines =
{
	.get_core_state   = ipanema_Simple_get_core_state,
	.new_prepare	  = ipanema_Simple_new_prepare,
	.new_place	  = ipanema_Simple_new_place,
	.new_end	  = ipanema_Simple_new_end,
	.tick		  = ipanema_Simple_tick,
	.yield		  = ipanema_Simple_yield,
	.block		  = ipanema_Simple_block,
	.unblock_prepare  = ipanema_Simple_unblock_prepare,
	.unblock_place	  = ipanema_Simple_unblock_place,
	.unblock_end	  = ipanema_Simple_unblock_end,
	.terminate	  = ipanema_Simple_detach,
	.schedule	  = ipanema_Simple_schedule,
	.newly_idle	  = ipanema_Simple_newly_idle,
	.enter_idle	  = ipanema_Simple_enter_idle,
	.exit_idle	  = ipanema_Simple_exit_idle,
	.balancing_select = ipanema_Simple_balancing,
	.core_entry	  = ipanema_Simple_core_entry,
	.core_exit	  = ipanema_Simple_core_exit,
	.init		  = ipanema_Simple_init,
	.free_metadata	  = ipanema_Simple_free_metadata,
	.can_be_default	  = ipanema_Simple_can_be_default,
	.attach		  = ipanema_Simple_attach
};

static int init_topology(void)
{
	struct topology_level *t = per_cpu(topology_levels, 0);
	size_t size;
	int i;

	Simple_ipa_nr_topology_levels = 0;

	while (t) {
		Simple_ipa_nr_topology_levels++;
		t = t->next;
	}

	size = Simple_ipa_nr_topology_levels * sizeof(struct list_head);
	Simple_ipa_topology = kzalloc(size, GFP_KERNEL);
	if (!Simple_ipa_topology) {
		Simple_ipa_nr_topology_levels = 0;
		return -ENOMEM;
	}

	for (i = 0; i < Simple_ipa_nr_topology_levels; i++) {
		INIT_LIST_HEAD(Simple_ipa_topology + i);
	}

	return 0;
}

static void destroy_scheduling_domains(void)
{
	struct Simple_ipa_sched_domain *sd, *tmp;
	int i;

	for (i = 0; i < Simple_ipa_nr_topology_levels; i++) {
		list_for_each_entry_safe(sd, tmp, Simple_ipa_topology + i,
					 siblings) {
			list_del(&sd->siblings);
			kfree(sd->groups);
			kfree(sd);
		}
	}

	kfree(Simple_ipa_topology);
}

static int create_scheduling_domains(unsigned int cpu)
{
	struct topology_level *t = per_cpu(topology_levels, cpu);
	struct Simple_ipa_core *c = &ipanema_core(cpu);
	size_t sd_size = sizeof(struct Simple_ipa_sched_domain);
	unsigned int level = 0;
	struct Simple_ipa_sched_domain *sd, *lower_sd = NULL;
	bool seen;

	c->sd = NULL;

	while (t) {
		/* if cpu is present in current level */
		seen = false;
		list_for_each_entry(sd, Simple_ipa_topology + level, siblings) {
			if (cpumask_test_cpu(cpu, &sd->cores)) {
				seen = true;
				break;
			}
		}
		if (!seen) {
			sd = kzalloc(sd_size, GFP_KERNEL);
			if (!sd)
				goto err;
			INIT_LIST_HEAD(&sd->siblings);
			sd->parent = NULL;
			sd->___sched_group_idx = 0;
			sd->groups = NULL;
			cpumask_copy(&sd->cores, &t->cores);
			sd->flags = t->flags;
			sd->next_balance = 0;
			sd->periodic_count = 0;
			sd->idle_count = 0;
			spin_lock_init(&sd->lock);
			list_add_tail(&sd->siblings, Simple_ipa_topology + level);
		}
		if (lower_sd)
			lower_sd->parent = sd;
		else
			c->sd = sd;

		if (seen)
			break;

		lower_sd = sd;
		t = t->next;
		level++;
	}

	return 0;

err:
	destroy_scheduling_domains();
	return -ENOMEM;
}

static int build_groups(struct Simple_ipa_sched_domain *sd,
			unsigned int lvl)
{
	struct Simple_ipa_sched_domain *sdl;
	struct Simple_ipa_sched_group *sg = NULL;
	int n = 0;

	list_for_each_entry(sdl, &Simple_ipa_topology[lvl - 1], siblings) {
		if (cpumask_subset(&sdl->cores, &sd->cores)) {
			n++;
			sg = krealloc(sg,
				      n * sizeof(struct Simple_ipa_sched_group),
				      GFP_KERNEL);
			if (!sg)
				goto err;

			cpumask_copy(&sg[n - 1].cores, &sdl->cores);
		}
	}

	sd->___sched_group_idx = n;
	sd->groups = sg;

	return 0;

err:
	destroy_scheduling_domains();
	return -ENOMEM;
}

static int build_lower_groups(struct Simple_ipa_sched_domain *sd)
{
	int cpu, n, i = 0;

	n = cpumask_weight(&sd->cores);
	sd->groups = kzalloc(n * sizeof(struct Simple_ipa_sched_group),
			     GFP_KERNEL);
	if (!sd->groups)
		goto fail;
	sd->___sched_group_idx = n;

	for_each_cpu(cpu, &sd->cores) {
		cpumask_clear(&sd->groups[i].cores);
		cpumask_set_cpu(cpu, &sd->groups[i].cores);
		i++;
	}

	return 0;

fail:
	destroy_scheduling_domains();
	return -ENOMEM;
}

/* Scheduling domains must be up to date for all CPUs */
static int create_scheduling_groups(void)
{
	struct Simple_ipa_sched_domain *sd = NULL;
	int i, ret;

	for (i = Simple_ipa_nr_topology_levels - 1; i > 0; i--) {
		list_for_each_entry(sd, &Simple_ipa_topology[i], siblings) {
			ret = build_groups(sd, i);
			if (ret)
				goto fail;
		}
	}

	list_for_each_entry(sd, Simple_ipa_topology, siblings) {
		ret = build_lower_groups(sd);
		if (ret)
			goto fail;
	}

	return 0;

fail:
	destroy_scheduling_domains();
	return -ENOMEM;
}

static void build_hierarchy(void)
{
	int cpu;

	init_topology();

	/* if unicore, don't build hierarchy */
	if (!Simple_ipa_nr_topology_levels)
		return;

	/* create hierarchy for all cpus */
	for_each_possible_cpu(cpu) {
		create_scheduling_domains(cpu);
	}
	create_scheduling_groups();
}

static int proc_show(struct seq_file *s, void *p)
{
	long cpu = (long) s->private;
	struct task_struct *pos, *n;
	struct Simple_ipa_process *pr, *curr_proc;
	int load_sum = 0;

	ipanema_lock_core(cpu);
	pr = ipanema_state(cpu).current_0;
	seq_printf(s, "CPU: %ld\n", cpu);
	seq_printf(s, "RUNNING (policy): %d (%d)\n",
	pr ? pr->task->pid : -1,
	pr ? pr->load : -1);
	n = per_cpu(ipanema_current, cpu);
	seq_printf(s, "RUNNING (runtime): %d\n", n ? n->pid : -1);
	load_sum += pr ? pr->load : 0;
	seq_printf(s, "READY: ");
	rbtree_postorder_for_each_entry_safe(pos, n,
					     &(ipanema_state(cpu).ready).root,
					     ipanema.node_runqueue) {
		curr_proc = (struct Simple_ipa_process *)policy_metadata(pos);
		load_sum += curr_proc->load;
		seq_printf(s, "%d (%d) -> ", pos->pid, curr_proc->load);
	}

	seq_printf(s, "\n");
	seq_printf(s, "COUNT(READY) = %d\n", count(IPANEMA_READY, cpu));
	seq_printf(s, "nr_ready = %d\n", ipanema_state(cpu).ready.nr_tasks);
	seq_printf(s, "load = %d\n", ipanema_core(cpu).cload);
	seq_printf(s, "load_sum = %d\n", load_sum);

	ipanema_unlock_core(cpu);

	return 0;
}

static int proc_open(struct inode *inode, struct file *file)
{
	long cpu;

	if (!kstrtol(file->f_path.dentry->d_iname, 10, &cpu))
		return single_open(file, proc_show, (void *)cpu);
	return -ENOENT;
}

static struct file_operations proc_fops = {

	.owner	 = THIS_MODULE,
	.open	 = proc_open,
	.read	 = seq_read,
	.llseek	 = seq_lseek,
	.release = single_release,
};

static int proc_topo_show(struct seq_file *s, void *p)
{
	int cpu, level, sd_lvl;
	struct Simple_ipa_core *c;
	struct Simple_ipa_sched_domain *sd;
	struct Simple_ipa_sched_group *sg;

	for_each_possible_cpu(cpu) {
		seq_printf(s, "cpu%d\n", cpu);
		c = &ipanema_core(cpu);
		for (level = 0; level < c->___sched_domains_idx; level++) {
			sd = &c->sd[level];
			seq_printf(s, "  +--> domain%d: %*pbl  [size=%d] (idle_count=%u, periodic_count=%u)\n",
				   level, cpumask_pr_args(&sd->cores),
				   cpumask_weight(&sd->cores),
				   sd->idle_count, sd->periodic_count);
			for (sd_lvl = 0; sd_lvl < sd->___sched_group_idx; sd_lvl++) {
				sg = &sd->groups[sd_lvl];
				seq_printf(s, "         +--> group%d: %*pbl\n",
					   sd_lvl, cpumask_pr_args(&sg->cores));
			}
		}
	}

	return 0;
}

static int proc_topo_open(struct inode *inode, struct file *file)
{
	return single_open(file, proc_topo_show, NULL);
}

static struct file_operations proc_topo_fops = {
	.owner   = THIS_MODULE,
	.open    = proc_topo_open,
	.read    = seq_read,
	.llseek  = seq_lseek,
	.release = single_release,
};

int init_module(void)
{
	int res, cpu;
	struct proc_dir_entry *procdir = NULL;
	char procbuf[10];

	/* Initialize scheduler variables with non-const value (function call) */
	for_each_possible_cpu(cpu) {
		ipanema_core(cpu).id = cpu;
		ipanema_core(cpu).cload = 0;
		/* READY rq */
		init_ipanema_rq(&ipanema_state(cpu).ready, RBTREE, cpu,
				IPANEMA_READY, ipanema_Simple_order_process);
	}

	/* Allocate & setup the ipanema_module */
	module = kzalloc(sizeof(struct ipanema_module), GFP_KERNEL);
	if (!module) {
		res = -ENOMEM;
		goto end;
	}

	/* build hierarchy with topology */
	build_hierarchy();

	strncpy(module->name, name, MAX_POLICY_NAME_LEN);
	module->routines = &ipanema_Simple_routines;
	module->kmodule = THIS_MODULE;

	/* Register module to the runtime */
	res = ipanema_add_module(module);
	if (res)
		goto clean_module;

	/* Create /proc/Simple/<cpu> and topology files */
	procdir = proc_mkdir(name, ipa_procdir);
	if (!procdir) {
		pr_info("%s: /proc/%s creation failed\n", name, name);
		goto clean_module;
	}
	for_each_possible_cpu(cpu) {
		scnprintf(procbuf, 10, "%d", cpu);
		if (!proc_create(procbuf, 0444, procdir, &proc_fops))
			pr_info("%s: /proc/%s/%s creation failed\n",
				name, name, procbuf);
	}
	if (!proc_create("topology", 0444, procdir, &proc_topo_fops))
		pr_info("%s: /proc/%s/topology creation failed\n",
			name, name);

	return 0;

 clean_module:
	kfree(module);
 end:
	return res;

}

void cleanup_module(void)
{
	int res;

	remove_proc_subtree(name, ipa_procdir);

	res = ipanema_remove_module(module);
	if (res) {
		pr_err("Cleanup failed (%d)\n", res);
		return;
	}

	kfree(module);
}

MODULE_AUTHOR("Ipanema Compiler");
MODULE_DESCRIPTION("Simple scheduling policy");
MODULE_LICENSE("GPL");
